/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bubble-sort-problem-proof': RouteRecordInfo<
      '/posts/bubble-sort-problem-proof',
      '/posts/bubble-sort-problem-proof',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GKD-rule-tutoil-attribute-1': RouteRecordInfo<
      '/posts/GKD-rule-tutoil-attribute-1',
      '/posts/GKD-rule-tutoil-attribute-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GKD-rule-tutoil-attribute-2': RouteRecordInfo<
      '/posts/GKD-rule-tutoil-attribute-2',
      '/posts/GKD-rule-tutoil-attribute-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GKD-rule-tutoil-selectors-1': RouteRecordInfo<
      '/posts/GKD-rule-tutoil-selectors-1',
      '/posts/GKD-rule-tutoil-selectors-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GKD-rule-tutoil-selectors-2': RouteRecordInfo<
      '/posts/GKD-rule-tutoil-selectors-2',
      '/posts/GKD-rule-tutoil-selectors-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/GKD-subscription-stop-maintain': RouteRecordInfo<
      '/posts/GKD-subscription-stop-maintain',
      '/posts/GKD-subscription-stop-maintain',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Make-GKD-Inspect-Better-development': RouteRecordInfo<
      '/posts/Make-GKD-Inspect-Better-development',
      '/posts/Make-GKD-Inspect-Better-development',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/milthm-reality-calculate': RouteRecordInfo<
      '/posts/milthm-reality-calculate',
      '/posts/milthm-reality-calculate',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/note': RouteRecordInfo<
      '/posts/note',
      '/posts/note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/P2669-solution': RouteRecordInfo<
      '/posts/P2669-solution',
      '/posts/P2669-solution',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/phylosophy-basic-question': RouteRecordInfo<
      '/posts/phylosophy-basic-question',
      '/posts/phylosophy-basic-question',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/QwQNT-ninth-event-answers-and-source-code': RouteRecordInfo<
      '/posts/QwQNT-ninth-event-answers-and-source-code',
      '/posts/QwQNT-ninth-event-answers-and-source-code',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/sabishii-natsu-no-seinishite-lyrics': RouteRecordInfo<
      '/posts/sabishii-natsu-no-seinishite-lyrics',
      '/posts/sabishii-natsu-no-seinishite-lyrics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sponsor/': RouteRecordInfo<
      '/sponsor/',
      '/sponsor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.10_ma_608aa334118f0938b835774fa9390094/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.10_@babel+parse_2e8428d9acfe3ca4327f9867997f9743/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.10_ma_608aa334118f0938b835774fa9390094/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.10_ma_608aa334118f0938b835774fa9390094/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/bubble-sort-problem-proof.md': {
      routes:
        | '/posts/bubble-sort-problem-proof'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/GKD-rule-tutoil-attribute-1.md': {
      routes:
        | '/posts/GKD-rule-tutoil-attribute-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/GKD-rule-tutoil-attribute-2.md': {
      routes:
        | '/posts/GKD-rule-tutoil-attribute-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/GKD-rule-tutoil-selectors-1.md': {
      routes:
        | '/posts/GKD-rule-tutoil-selectors-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/GKD-rule-tutoil-selectors-2.md': {
      routes:
        | '/posts/GKD-rule-tutoil-selectors-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/GKD-subscription-stop-maintain.md': {
      routes:
        | '/posts/GKD-subscription-stop-maintain'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Make-GKD-Inspect-Better-development.md': {
      routes:
        | '/posts/Make-GKD-Inspect-Better-development'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/milthm-reality-calculate.md': {
      routes:
        | '/posts/milthm-reality-calculate'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/note.md': {
      routes:
        | '/posts/note'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/P2669-solution.md': {
      routes:
        | '/posts/P2669-solution'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/phylosophy-basic-question.md': {
      routes:
        | '/posts/phylosophy-basic-question'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/QwQNT-ninth-event-answers-and-source-code.md': {
      routes:
        | '/posts/QwQNT-ninth-event-answers-and-source-code'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/sabishii-natsu-no-seinishite-lyrics.md': {
      routes:
        | '/posts/sabishii-natsu-no-seinishite-lyrics'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/sponsor/index.md': {
      routes:
        | '/sponsor/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
